### ISSUE TITLE
Sorry! Incorrect email or password. Try again.

### ISSUE THREAD

**Issue by randrewright** [Junaidk11/InventoryApp#2]
I keep getting this error. "Sorry! Incorrect email or password. Try again."

 The database connects fine but it cannot find the email or password in the data tables. What should the tables be named? What are the data types?

**Comment by Junaidk11** [comment]
Have you registered your email and created a password?

**Comment by Junaidk11** [comment]
I've just added a user manual pdf, it will walk you through setting up the application locally.

**Comment by randrewright** [comment]
Ok thank you! I will try on Monday.

*Randré Wright*


*Confidentiality Notice*:

This electronic transmission message is intended only for the use of the
individual or entity to which it is addressed. The information in this
transmission may be proprietary, confidential, privileged and exempt from
disclosure under applicable law. If the reader of this Notice is not the
intended recipient (or the employee or agent responsible for delivering the
message to the intended recipient), you are hereby notified that any use,
dissemination, distribution or copying of this communication is prohibited.
If you have received this communication in error, please immediately
notify me by telephone or by e-mail and destroy the materials transmitted
to you in error. Thank you for your cooperation.
